// <auto-generated />
using System;
using DriverApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriverApi.Migrations
{
    [DbContext(typeof(DriverDbContext))]
    partial class DriverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DriverApi.Models.Driver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DriverId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DriverApi.Models.DriverAnalytics", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("AvgTripSpeed")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("DriverScore")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.ToTable("DriverAnalytics");
                });

            modelBuilder.Entity("DriverApi.Models.Telemetry", b =>
                {
                    b.Property<string>("SampleId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("CalculatedSpeed")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime>("CurTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("SampleId");

                    b.HasIndex("TripId");

                    b.ToTable("TelemetrySamples");
                });

            modelBuilder.Entity("DriverApi.Models.Trip", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("TripId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("DriverApi.Models.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VehicleId");

                    b.HasIndex("DriverId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DriverApi.Models.DriverAnalytics", b =>
                {
                    b.HasOne("DriverApi.Models.Driver", "Driver")
                        .WithOne("Analytics")
                        .HasForeignKey("DriverApi.Models.DriverAnalytics", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DriverApi.Models.Telemetry", b =>
                {
                    b.HasOne("DriverApi.Models.Trip", "Trip")
                        .WithMany("TelemetrySamples")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DriverApi.Models.Trip", b =>
                {
                    b.HasOne("DriverApi.Models.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriverApi.Models.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DriverApi.Models.Vehicle", b =>
                {
                    b.HasOne("DriverApi.Models.Driver", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DriverApi.Models.Driver", b =>
                {
                    b.Navigation("Analytics");

                    b.Navigation("Trips");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DriverApi.Models.Trip", b =>
                {
                    b.Navigation("TelemetrySamples");
                });

            modelBuilder.Entity("DriverApi.Models.Vehicle", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
